# Generated by Django 4.2.9 on 2026-03-06 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_user', models.CharField(max_length=40)),
                ('room_slug', models.CharField(max_length=50)),
                ('trigger_msg', models.TextField()),
                ('risk_level', models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crisis_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
