# Generated by Django 4.2.9 on 2026-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
