# Generated by Django 4.2.9 on 2026-05-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
